#!/bin/bash
cat << _EOF_ > /var/cw/systeam/.myvars
function sett() {
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1=${ORIG}${TITLE}
}
_EOF_

source /var/cw/systeam/.myvars
