name: IP Check and Update Cloudfront IPs

on:
  schedule:
    - cron: "0 20 * * *"
  push:
    branches: [ master ]

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check and update IPs List
        id: update
        run: |
          # Fetch the IP list from the URL
          IP_LIST=$(curl -s https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips)

          # Format the IP list for nginx configuration
          CONFIG=""
          for IP in $(echo $IP_LIST | jq -r '.CLOUDFRONT_GLOBAL_IP_LIST[]'); do
            CONFIG+="set_real_ip_from $IP;\n"
          done

          # Check if the downloaded IP configuration file is different
          if [[ ! -f cloudfront-realip.conf || "$(cat cloudfront-realip.conf)" != "$CONFIG" ]]; then
            # Create or update the IP configuration file
            echo -e "$CONFIG" > cloudfront-realip.conf

            # Configure git
            git config --global user.name "Afraz Ahmed"
            git config --global user.email "aphraz@live.com"

            # Commit and push changes to the public GitHub repository
            git add cloudfront-realip.conf
            git diff-index --quiet HEAD || git commit -m "Update IP configuration" && git push
          else
            echo "No changes found. Skipping commit and push."
          fi

