name: IP Check and Update

on:
  schedule:
    - cron: "0 14 * * 5"

jobs:
  update-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Check and update IPs
        run: |
          # Fetch the IP list from the URL
          IP_LIST=$(curl -s https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips)

          # Format the IP list for nginx configuration
          CONFIG=""
          for IP in $(echo $IP_LIST | jq -r '.CLOUDFRONT_GLOBAL_IP_LIST[]'); do
            CONFIG+="set_real_ip_from $IP;\n"
          done

          # Create or update the IP configuration file
          echo -e "$CONFIG" > cloudfront-realip.conf

          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Commit and push changes to the public GitHub repository
          REPO_URL="https://github.com/aphraz/cloudways.git"
          git clone "$REPO_URL"
          cd cloudways
          git add cloudfront-realip.conf
          git commit -m "Update IP configuration"
          git push "$REPO_URL" HEAD:main
